version: "3"
services:
  database:
    container_name: db
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: djangostripe